services:
  # PostgreSQL Database
  - type: pserv
    name: cannabis-farm-db
    env: postgresql
    plan: free
    databaseName: cannabis_farm
    user: cannabis_user

  # Web Application
  - type: web
    name: cannabis-farm-app
    env: python
    region: oregon
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    healthCheckPath: "/"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8
      - key: SECRET_KEY
        generateValue: true
      - key: MAIL_USERNAME
        value: donny21001@gmail.com
      - key: MAIL_PASSWORD
        sync: false  # You'll set this manually in Render dashboard
      - key: RENDER
        value: "true"
      - key: DATABASE_URL
        fromDatabase:
          name: cannabis-farm-db
          property: connectionString